name: 'ksync'
description: 'Syncs files via rsync to pods'
inputs:
  cluster:
    description: 'EKS Fargate cluster name'
    required: true
  namespace:
    description: 'the namespaces where you ms lives'
    required: true
  app:
    description: 'the name of your app selector'
    required: true
  source_dir:
    description: 'the name of your repo folder'
    required: true
  dest_dir:
    description: 'the name of your dest folder'
    required: true
  kubeconfig:
    description: 'the name of your dest folder'
    required: false
    default: '/github/home'

outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cluster }}
    - ${{ inputs.namespace }}
    - ${{ inputs.app }}
    - ${{ inputs.source_dir }}
    - ${{ inputs.dest_dir }}
    - ${{ inputs.kubeconfig }}
