name: 'ksync'
description: 'Syncs files via rsync to pods'
inputs:
  namespace:
    description: 'the namespaces where you ms lives'
    required: true
  app:
    description: 'the name of your app selector'
    required: true
  dir:
    description: 'the name of your app selector'
    required: true

outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.namespace }}
    - ${{ inputs.app }}
    - ${{ dir.app }}
